Prettier and husky
MaksymNaboka/bl-mobile-app pull request #2
Opened 2024-06-20 01:04 UTC by MaksymNaboka

2024-06-20 05:56 UTC, denisorda reviewed
You should merge all these commits into several or one and avoid not informative commit messages. Commits tree must be easier for read. For merge pull requests pls use rebase instead merge.

2024-06-20 05:56 UTC, denisorda commented on app/(tabs)/_layout.tsx
> +import React from "react";
pls, put import from react to first line in all files

2024-06-20 05:56 UTC, denisorda commented on components/Collapsible.tsx
> +export function Collapsible({
pls, add empty line between imports and functional component

2024-06-20 19:15 UTC, avkos requested changes

2024-06-20 19:15 UTC, avkos commented on .husky/pre-commit
> +exit 1
please remove 
```
echo debug debug debug
exit 1
```

2024-06-20 19:15 UTC, avkos commented on app/(tabs)/_layout.tsx
> +import React from "react";
with expo lint we do need to import react in each component

2024-06-21 17:01 UTC, avkos requested changes

2024-06-21 17:01 UTC, avkos commented on package.json
> +    "husky": "^9.0.11",
I received `sh: prettier: command not found`
add prettier to dev dependencies

2024-06-21 17:16 UTC, MaksymNaboka commented on package.json
> +    "husky": "^9.0.11",
updated

2024-06-21 17:17 UTC, avkos approved these changes

2024-06-21 17:21 UTC, merged